namespace Sadie.Shared.Networking;

public class ServerPacketId
{
    public const short SecureLogin = 2491;
    public const short PlayerHomeRoom = 2875;
    public const short UniqueMachineId = 1488;
    public const short PlayerEffectList = 340;
    public const short PlayerClothingList = 1450;
    public const short NoobnessLevel = 3738;
    public const short PlayerPermissions = 411;
    public const short PlayerStatus = 2033;
    public const short PlayerData = 2725;
    public const short PlayerPerks = 2586;
    public const short PlayerClubMembership = 954;
    public const short NavigatorMetaData = 3052;
    public const short NavigatorLiftedRooms = 3104;
    public const short NavigatorCollapsedCategories = 1543;
    public const short NavigatorEventCategories = 3244;
    public const short NavigatorSavedSearches = 3984;
    public const short NavigatorSettings = 518;
    public const short PlayerMessengerInit = 1605;
    public const short PlayerFriendsList = 3130;
    public const short PlayerPong = 10;
    public const short HotelViewData = 1745;
    public const short PlayerMeMenuSettings = 513;
    public const short HotelViewBonusRare = 1533;
    public const short PlayerIgnoredUsers = 126;
    public const short GameCentreConfig = 2265;
    public const short NavigatorPromotedRooms = 52;
    public const short RoomCategories = 1562;
    public const short PlayerFriendRequests = 280;
    public const short PlayerSanctionStatus = 2221;
    public const short RoomLoaded = 758;
    public const short RoomData = 2031;
    public const short RoomPaint = 2454;
    public const short RoomRelativeMap = 2753;
    public const short RoomHeightMap = 1301;
    public const short PlayerActivityPointsBalance = 2018;
    public const short PlayerCreditsBalance = 3475;
    public const short NotificationSettings = 3284;
    public const short PlayerAchievementScore = 1968;
    public const short RoomUserStatus = 1640;
    public const short RoomUserData = 374;
    public const short RoomUserChat = 1446;
    public const short RoomUserShout = 1036;
    public const short RoomUserLeft = 2661;
    public const short RoomUserDance = 2233;
    public const short RoomUserAction = 1631;
    public const short RoomUserTyping = 1717;
    public const short NavigatorRooms = 2690;
    public const short PlayerChangedAppearance = 2429;
}