<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.7.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0-preview.3.25171.5" />
      <PackageReference Include="Sadie.API" Version="6.0.3" />
      <PackageReference Include="Scrutor" Version="6.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sadie.Networking.Events\Sadie.Networking.Events.csproj" />
      <ProjectReference Include="..\Sadie.Networking.Writers\Sadie.Networking.Writers.csproj" />
    </ItemGroup>
</Project>
