<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Sadie.API">
        <HintPath>..\..\..\..\..\..\home\a\.nuget\packages\sadie.api\5.9.2\lib\net10.0\Sadie.API.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sadie.Core\Sadie.Core.csproj" />
    </ItemGroup>

</Project>
